=== UO283535/PropioLucia/EscritorioVirtual/xml/rutas.dtd
<!ELEMENT rutas (ruta*)>
<!ELEMENT ruta (nombre, tipo, transporte, fecha_inicio?, hora_inicio?, duracion, agencia, descripcion, 
personasAdecuadas, lugar_inicio, direccion_inicio, coordenada_inicio, referencias, bibliografia, recomendacion, hitos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT hora_inicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personasAdecuadas (#PCDATA)>
<!ELEMENT lugar_inicio (#PCDATA)>
<!ELEMENT direccion_inicio (#PCDATA)>
<!ELEMENT coordenada_inicio (longitud, latitud , altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT referencias (referencia*)>
<!ELEMENT bibliografia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (hito*)>
<!ELEMENT referencia (#PCDATA)>
<!ATTLIST referencia src CDATA #REQUIRED>
<!ELEMENT hito (nombreHito, descripcionHito, coordenadaHito, distanciaHito, fotografiasHito, videosHito)>
<!ELEMENT nombreHito (#PCDATA)>
<!ELEMENT descripcionHito (#PCDATA)>
<!ELEMENT coordenadaHito (longitud, latitud, altitud)>
<!ELEMENT distanciaHito (#PCDATA)>
<!ELEMENT fotografiasHito (fotografiaHito*)>
<!ELEMENT fotografiaHito (#PCDATA)>
<!ATTLIST fotografiaHito src CDATA #REQUIRED>
<!ELEMENT videosHito (videoHito*)>
<!ELEMENT videoHito (#PCDATA)>
<!ATTLIST videoHito src CDATA #REQUIRED>

=== UO283535/PropioLucia/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
  <ruta>
    <nombre>Ruta por Seúl</nombre>
    <tipo>Ciudad</tipo>
    <transporte>Metro y a pie</transporte>
    <duracion>2 días</duracion>
    <agencia>Visit Korea</agencia>
    <descripcion>Explora la capital de Corea del Sur, Seúl, y descubre su rica historia y cultura.</descripcion>
    <personasAdecuadas>Turistas interesados en la historia y la gastronomía.</personasAdecuadas>
    <lugar_inicio>Palacio de Gyeongbokgung</lugar_inicio>
    <direccion_inicio>161 Sajik-ro, Jongno-gu, Seúl</direccion_inicio>
    <coordenada_inicio>
      <longitud>126.977966</longitud>
      <latitud>37.577262</latitud>
      <altitud>51 metros</altitud>
    </coordenada_inicio>
    <referencias>
        <referencia src=" "></referencia>
    </referencias>
    <bibliografia>Guía turística de Seúl</bibliografia>
    <recomendacion>Lleva calzado cómodo y un paraguas, ya que el clima puede ser impredecible.</recomendacion>
    <hitos>
      <hito>
        <nombreHito>Palacio de Gyeongbokgung</nombreHito>
        <descripcionHito>Un majestuoso palacio real de la dinastía Joseon.</descripcionHito>
        <coordenadaHito>
          <longitud>126.98966</longitud>
          <latitud>39.58262</latitud>
          <altitud>52 metros</altitud>
        </coordenadaHito>
        <distanciaHito>0 km desde el inicio</distanciaHito>
        <fotografiasHito>
          <fotografiaHito src="gyeongbokgung.jpg" />
        </fotografiasHito>
        <videosHito>
          <videoHito src="gyeongbokgung.mp4" />
        </videosHito>
      </hito>
      <!-- Otros hitos de la ruta -->
      <hito>
        <nombreHito>Deoksugung</nombreHito>
        <descripcionHito>Un majestuoso palacio real de la dinastía Joseon.</descripcionHito>
        <coordenadaHito>
          <longitud>126.9749</longitud>
          <latitud>37.5652</latitud>
          <altitud>52 metros</altitud>
        </coordenadaHito>
        <distanciaHito>2 km desde el inicio</distanciaHito>
        <fotografiasHito>
          <fotografiaHito src="gyeongbokgung.jpg" />
        </fotografiasHito>
        <videosHito>
          <videoHito src="gyeongbokgung.mp4" />
        </videosHito>
      </hito>
      <hito>
        <nombreHito>Seoul Tower</nombreHito>
        <descripcionHito>Un majestuoso palacio real de la dinastía Joseon.</descripcionHito>
        <coordenadaHito>
          <longitud>126.988276</longitud>
          <latitud>37.551216</latitud>
          <altitud>239 metros</altitud>
        </coordenadaHito>
        <distanciaHito>10 km desde el inicio</distanciaHito>
        <fotografiasHito>
          <fotografiaHito src="gyeongbokgung.jpg" />
        </fotografiasHito>
        <videosHito>
          <videoHito src="gyeongbokgung.mp4" />
        </videosHito>
      </hito>
    </hitos>
  </ruta>
 <ruta>
      <nombre>Ruta por Busan</nombre>
      <tipo>Ciudad y Playa</tipo>
      <transporte>Autobús y ferry</transporte>
      <duracion>3 días</duracion>
      <agencia>Korea Travel Co.</agencia>
      <descripcion>Descubre la ciudad costera de Busan y disfruta de sus hermosas playas y mariscos frescos.</descripcion>
      <personasAdecuadas>Aventureros y amantes de la playa.</personasAdecuadas>
      <lugar_inicio>Estación de autobuses de Busan</lugar_inicio>
      <direccion_inicio>15-1 Gudeok-ro, Gudeok-myeon, Gimhae, Gyeongsangnam-do</direccion_inicio>
      <coordenada_inicio>
        <longitud>128.938596</longitud>
        <latitud>35.166642</latitud>
        <altitud>10 metros</altitud>
      </coordenada_inicio>
      <referencias>
        <referencia src=" "></referencia>
    </referencias>
      <bibliografia>Guía de viaje de Busan</bibliografia>
      <recomendacion>Lleva protector solar y traje de baño para disfrutar de la playa.</recomendacion>
      <hitos>
        <hito>
          <nombreHito>Playa de Haeundae</nombreHito>
          <descripcionHito>Una de las playas más famosas de Corea del Sur.</descripcionHito>
          <coordenadaHito>
            <longitud>129.16215</longitud>
            <latitud>35.15768</latitud>
            <altitud>0 metros</altitud>
          </coordenadaHito>
          <distanciaHito>0 km desde el inicio</distanciaHito>
          <fotografiasHito>
            <fotografiaHito src="gyeongbokgung.jpg" />
          </fotografiasHito>
          <videosHito>
            <videoHito src="gyeongbokgung.mp4" />
          </videosHito>
        </hito>

        <!-- Otros hitos de la ruta -->
        <hito>
          <nombreHito>Beomeosa</nombreHito>
          <descripcionHito>Una de las playas más famosas de Corea del Sur.</descripcionHito>
          <coordenadaHito>
            <longitud>129.1028</longitud>
            <latitud>35.2285</latitud>
            <altitud>1 metros</altitud>
          </coordenadaHito>
          <distanciaHito>0 km desde el inicio</distanciaHito>
          <fotografiasHito>
            <fotografiaHito src="gyeongbokgung.jpg" />
          </fotografiasHito>
          <videosHito>
            <videoHito src="gyeongbokgung.mp4" />
          </videosHito>
        </hito>
        <hito>
          <nombreHito>Gamcheon Culture Village</nombreHito>
          <descripcionHito>Una de las playas más famosas de Corea del Sur.</descripcionHito>
          <coordenadaHito>
            <longitud>129.009</longitud>
            <latitud>35.097</latitud>
            <altitud>10 metros</altitud>
          </coordenadaHito>
          <distanciaHito>0 km desde el inicio</distanciaHito>
          <fotografiasHito>
            <fotografiaHito src="gyeongbokgung.jpg" />
          </fotografiasHito>
          <videosHito>
            <videoHito src="gyeongbokgung.mp4" />
          </videosHito>
        </hito>
      </hitos>
    </ruta>
        <ruta>
          <nombre>Ruta por Gyeongju</nombre>
          <tipo>Ciudad y Patrimonio Cultural</tipo>
          <transporte>Tren y a pie</transporte>
          <fecha_inicio>24/10/2023</fecha_inicio>
          <hora_inicio>09:00</hora_inicio>
          <duracion>2 días</duracion>
          <agencia>Cultural Heritage Tours</agencia>
          <descripcion>Explora la ciudad de Gyeongju y sumérgete en su rica herencia cultural y arqueológica.</descripcion>
          <personasAdecuadas>Amantes de la historia y la arqueología.</personasAdecuadas>
          <lugar_inicio>Estación de tren de Gyeongju</lugar_inicio>
          <direccion_inicio>73-1, Hwango-dong, Gyeongju, Gyeongsangbuk-do</direccion_inicio>
          <coordenada_inicio>
            <longitud>129.215028</longitud>
            <latitud>35.840599</latitud>
            <altitud>10 metros</altitud>
          </coordenada_inicio>
          <referencias>
            <referencia src=" "></referencia>
        </referencias>
          <bibliografia>Guía de Gyeongju</bibliografia>
         
          <recomendacion>Lleva calzado cómodo y una cámara para capturar los sitios históricos.</recomendacion>
          <hitos>
            <hito>
              <nombreHito>Túmulos Reales de Gyeongju</nombreHito>
              <descripcionHito>Sitios de entierro de la realeza de la dinastía Silla.</descripcionHito>
              <!-- Detalles del hito -->
              <coordenadaHito>
                <longitud>129.211</longitud>
                <latitud>35.781</latitud>
                <altitud>16 metros</altitud>
              </coordenadaHito>
              <distanciaHito>0 km desde el inicio</distanciaHito>
              <fotografiasHito>
                <fotografiaHito src="gyeongbokgung.jpg" />
              </fotografiasHito>
              <videosHito>
                <videoHito src="gyeongbokgung.mp4" />
              </videosHito>
            </hito>
            <!-- Otros hitos de la ruta -->
          </hitos>
        </ruta>
  </rutas>
